/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class GTPL_UG {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new GTPL_UG().getGreeting());
    }
}
